export interface TemplateChallenge {
  title: string;
  description?: string;
  points: number;
}

export interface Template {
  id: string;
  name: string;
  emoji: string;
  description: string;
  challenges: TemplateChallenge[];
}

export const templates: Template[] = [
  {
    id: 'mariage',
    name: 'Mariage',
    emoji: '\u{1F492}',
    description: '20 defis pour animer votre mariage',
    challenges: [
      { title: 'Photo avec les maries', points: 10 },
      { title: 'Selfie sur la piste de danse', points: 5 },
      { title: 'Photo du gateau', points: 5 },
      { title: 'Reproduire la pose des maries', points: 15 },
      { title: 'Photo avec 3 generations', points: 10 },
      { title: 'Attraper le bouquet (ou essayer)', points: 15 },
      { title: 'Faire un coeur avec les mains a deux', points: 5 },
      { title: 'Photo avec un inconnu', points: 10 },
      { title: 'Selfie avec le temoin', points: 10 },
      { title: 'Photo la plus romantique possible', points: 15 },
      { title: 'Danser comme si personne ne regardait', points: 10 },
      { title: 'Porter quelqu un en mode princesse', points: 10 },
      { title: 'Photo de groupe de 10+ personnes', points: 15 },
      { title: 'Faire pleurer quelqu un de joie', points: 20 },
      { title: 'Photo avec la decoration florale', points: 5 },
      { title: 'Imiter la demarche des maries', points: 10 },
      { title: 'Selfie avec le DJ', points: 5 },
      { title: 'Photo la plus drole de la soiree', points: 15 },
      { title: 'Embrasser quelqu un sur la joue', points: 5 },
      { title: 'Derniere photo de la soiree', points: 20 },
    ],
  },
  {
    id: 'anniversaire',
    name: 'Anniversaire',
    emoji: '\u{1F382}',
    description: '15 defis pour un anniversaire memorable',
    challenges: [
      { title: 'Photo avec la star du jour', points: 10 },
      { title: 'Selfie devant le gateau', points: 5 },
      { title: 'Faire la grimace la plus drole', points: 10 },
      { title: 'Photo de groupe', points: 10 },
      { title: 'Reproduire une photo d enfance', points: 15 },
      { title: 'Cul sec !', points: 10 },
      { title: 'Photo avec de la nourriture dans la bouche', points: 5 },
      { title: 'Selfie aux toilettes', points: 5 },
      { title: 'Porter les chaussures de quelqu un d autre', points: 10 },
      { title: 'Faire rire quelqu un qui ne veut pas rire', points: 15 },
      { title: 'Se dessiner une moustache et poser', points: 10 },
      { title: 'Photo sous la table', points: 10 },
      { title: 'Danser avec un balai', points: 10 },
      { title: 'Faire semblant de dormir dans un endroit insolite', points: 15 },
      { title: 'Photo la plus stylee possible', points: 10 },
    ],
  },
  {
    id: 'evg-evjf',
    name: 'EVG / EVJF',
    emoji: '\u{1F389}',
    description: '20 defis pour un enterrement de vie memorable',
    challenges: [
      { title: 'Photo avec la future mariee / le futur marie', points: 5 },
      { title: 'Faire une pyramide humaine', points: 20 },
      { title: 'Demande en mariage a un inconnu', points: 20 },
      { title: 'Porter quelqu un en mode princesse', points: 10 },
      { title: 'Se cacher dans un endroit improbable', points: 10 },
      { title: 'Convaincre 4 personnes de faire la meme grimace', points: 15 },
      { title: 'Faire des pompes avec quelqu un sur le dos', points: 15 },
      { title: 'Faire le grand ecart (ou essayer)', points: 10 },
      { title: 'Boire un verre en poirier', points: 15 },
      { title: 'Lecher le coude de quelqu un', points: 10 },
      { title: 'Se faire porter sur le dos', points: 10 },
      { title: 'Faire un bras de fer', points: 10 },
      { title: 'Prendre un couple en photo', points: 5 },
      { title: 'Reproduire un tableau celebre', points: 15 },
      { title: 'Selfie avec quelqu un qui ne s en rend pas compte', points: 10 },
      { title: 'Boire dans le verre de quelqu un en douce', points: 10 },
      { title: 'Tenir en equilibre avec un verre sur la tete', points: 15 },
      { title: 'Faire une declaration d amour a un objet', points: 10 },
      { title: 'Chanter une chanson a un inconnu', points: 15 },
      { title: 'Photo de fin de soiree', points: 10 },
    ],
  },
  {
    id: 'team-building',
    name: 'Team Building',
    emoji: '\u{1F3E2}',
    description: '15 defis pour souder votre equipe',
    challenges: [
      { title: 'Selfie d equipe', points: 5 },
      { title: 'Photo avec le / la boss', points: 10 },
      { title: 'Reproduire le logo de l entreprise avec vos corps', points: 20 },
      { title: 'La pose la plus corporate possible', points: 10 },
      { title: 'Photo avec quelqu un d un autre service', points: 10 },
      { title: 'Faire un compliment a un collegue', points: 10 },
      { title: 'Tour la plus haute en gobelets', points: 15 },
      { title: 'Photo la plus creative avec un objet de bureau', points: 15 },
      { title: 'Imiter un collegue (les autres devinent)', points: 10 },
      { title: 'Photo de groupe de 10+ personnes', points: 15 },
      { title: 'Le sourire le plus force possible', points: 5 },
      { title: 'Faire rire votre manager', points: 15 },
      { title: 'Photo la plus synchronisee a 3+', points: 15 },
      { title: 'Trouver quelqu un qui porte la meme couleur', points: 5 },
      { title: 'La meilleure pose de super-heros', points: 10 },
    ],
  },
  {
    id: 'soiree',
    name: 'Soiree entre amis',
    emoji: '\u{1F37B}',
    description: '15 defis pour une soiree de folie',
    challenges: [
      { title: 'Cul sec !', points: 10 },
      { title: 'Photo sous la table', points: 5 },
      { title: 'Selfie aux toilettes', points: 5 },
      { title: 'Danser avec un balai', points: 10 },
      { title: 'Faire la grimace la plus laide', points: 10 },
      { title: 'Porter les chaussures de quelqu un d autre', points: 10 },
      { title: 'Se dessiner une moustache', points: 10 },
      { title: 'Photo avec de la nourriture dans la bouche', points: 5 },
      { title: 'Prendre quelqu un en flagrant delit', points: 15 },
      { title: 'Faire semblant de dormir quelque part', points: 10 },
      { title: 'Photo la plus floue possible', points: 5 },
      { title: 'Selfie avec quelqu un qui ne s en rend pas compte', points: 10 },
      { title: 'Empiler le plus de trucs sur la tete', points: 15 },
      { title: 'Faire rire quelqu un qui ne veut pas', points: 15 },
      { title: 'Photo de fin de soiree', points: 10 },
    ],
  },
];